### ISSUE TITLE
Error when using STModiCluster 

### ISSUE THREAD

**Issue by jestlin15** [Yelab2020/Cottrazm#10]
Hihi can I please get help for this error? 

When I run this code I get the error below. 
```
TumorST <- STModiCluster(InDir = InDir, Sample = Sample, OutDir = OutDir, TumorST = TumorST, res = 1.5)
P1T start SME normalize
```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  TypeError: decoding str is not supported
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Cottrazm/python/Rusedtile.py", line 21, in ME_normalize
    data=st.Read10X(path = inDir)
  File "/Users/jes/anaconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/wrapper/read.py", line 96, in Read10X
    library_id_raw = attrs.pop("library_ids")[0]
TypeError: decoding str is not supported

── R Traceback ──────────────────────────────────────────────────────────────
    ▆
 1. └─Cottrazm::STModiCluster(...)
 2.   └─reticulate (local) ME_normalize(inDir = InDir, outDir = OutDir, sample = Sample)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 
 My stlearn version is 0.4.12

**Comment by ShengFang-0829** [comment]
Specific error details need to be checked. 
Perhaps there is an issue with this package keras.
raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- [Errno 104] Connection reset by peer
**Solution：**
You can download the H5 data file locally in advance(Linux:$HOME/.keras/models,Windows:python package file settings/.keras/models/).

**Comment by xzz-1995** [comment]
This problem might arise from Stlearn Read10X funcion, when I checked the current vision (1.0.1) the code in '.../stlearn/wrapper/read.py' changed to: library_id = str(attrs.pop("library_ids")[0], "utf-8"). So, I think you might need to update your Stlearn version, then the TypeError  about str might be solved.

**Comment by daswind** [comment]
I have the same question. Do you konw which one is the right type for avoid package conflicts? Thank you.

**Comment by ConDem94** [comment]
> Hihi can I please get help for this error? 
> 
> 
> 
> When I run this code I get the error below. 
> 
> ```
> 
> TumorST <- STModiCluster(InDir = InDir, Sample = Sample, OutDir = OutDir, TumorST = TumorST, res = 1.5)
> 
> P1T start SME normalize
> 
> ```
> 
> Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
> 
>   TypeError: decoding str is not supported
> 
> Run `reticulate::py_last_error()` for details.
> 
> > reticulate::py_last_error()
> 
> 
> 
> ── Python Exception Message ─────────────────────────────────────────────────
> 
> Traceback (most recent call last):
> 
>   File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Cottrazm/python/Rusedtile.py", line 21, in ME_normalize
> 
>     data=st.Read10X(path = inDir)
> 
>   File "/Users/jes/anaconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/wrapper/read.py", line 96, in Read10X
> 
>     library_id_raw = attrs.pop("library_ids")[0]
> 
> TypeError: decoding str is not supported
> 
> 
> 
> ── R Traceback ──────────────────────────────────────────────────────────────
> 
>     ▆
> 
>  1. └─Cottrazm::STModiCluster(...)
> 
>  2.   └─reticulate (local) ME_normalize(inDir = InDir, outDir = OutDir, sample = Sample)
> 
>  3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
> 
>  
> 
>  My stlearn version is 0.4.12

Hi, did you find a solution to this? I'm encountering the same issue.

**Comment by caoy0111** [comment]
I am counting a similar problem, and it real bother me a lot. <html> TumorST = STModiCluster(InDir = InDir, Sample = Sample, OutDir = OutDir, 
+                         TumorST = TumorST, res = res)

Error in py_call_impl(callable, call_args$unnamed, call_args$named) :    TypeError: No conversion path for dtype: dtype('<U') Run `reticulate::py_last_error()` for details. Called from: py_call_impl(callable, call_args$unnamed, call_args$named) Browse[1]> reticulate::py_last_error()  ── Python Exception Message ─────────────────────────────────────────────────────────── Traceback (most recent call last):   File "/home/RRR/Cottrazm/python/Rusedtile.py", line 21, in ME_normalize     data=st.Read10X(path = inDir)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/wrapper/read.py", line 86, in Read10X     adata = read_visium(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/scanpy/readwrite.py", line 373, in read_visium     adata = read_10x_h5(path / count_file, genome=genome)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/scanpy/readwrite.py", line 198, in read_10x_h5     adata = _read_legacy_10x_h5(filename, genome=genome, start=start)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/scanpy/readwrite.py", line 241, in _read_legacy_10x_h5     adata = AnnData(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/anndata/_core/anndata.py", line 291, in __init__     self._init_as_actual(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/anndata/_core/anndata.py", line 487, in _init_as_actual     self._obs = _gen_dataframe(obs, self._n_obs, ["obs_names", "row_names"])   File "/home/.conda/envs/TumorBoundary/lib/python3.8/functools.py", line 875, in wrapper     return dispatch(args[0].__class__)(*args, **kw)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/anndata/_core/anndata.py", line 105, in _gen_dataframe     return pd.DataFrame(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/frame.py", line 664, in __init__     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 443, in dict_to_mgr     arrays = Series(data, index=columns, dtype=object)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/series.py", line 436, in __init__     data, index = self._init_dict(data, index, dtype)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/series.py", line 529, in _init_dict     s = create_series_with_explicit_dtype(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/construction.py", line 915, in create_series_with_explicit_dtype     return Series(   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/series.py", line 470, in __init__     data = sanitize_array(data, index, dtype, copy)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/construction.py", line 622, in sanitize_array     subarr = _try_cast(data, dtype, copy, raise_cast_failure)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/construction.py", line 809, in _try_cast     subarr = construct_1d_object_array_from_listlike(arr)   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1784, in construct_1d_object_array_from_listlike     result[:] = values   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 217, in __array__     data = self[:]   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 207, in __getitem__     return self._dset.__getitem__(args, new_dtype=self._dtype)   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper   File "/home/.conda/envs/TumorBoundary/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 781, in __getitem__     mtype = h5t.py_create(new_dtype)   File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create   File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create   File "h5py/h5t.pyx", line 1753, in h5py.h5t.py_create TypeError: No conversion path for dtype: dtype('<U')  ── R Traceback ────────────────────────────────────────────────────────────────────────     ▆  1. └─global STModiCluster(...)  2.   └─reticulate (local) ME_normalize(inDir = InDir, outDir = OutDir, sample = Sample)  3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named) Browse[1]> Q
--
 
Did anybody knews?

**Comment by wangtonglian** [comment]
I also ran into the same problem and adjusted it as follows:
1.Downgraded the package version
pip install "numba==0.57.1" "numpy>=1.18,<1.22" --force-reinstall 
2.Modified the absolute path handling: previously used ~ to represent the home directory, but later changed it to the /home/user/ format, after which the program ran successfully.
Should the problem remain unresolved, you're welcome to reach out to me at [sxdycai@126.com](mailto:sxdycai@126.com) for joint learning and discussion.

<img width="976" height="233" alt="Image" src="https://github.com/user-attachments/assets/2c3149d3-31eb-4e7d-b4da-2420d100d244" />
