### ISSUE TITLE
STModiCluster error

### ISSUE THREAD

**Issue by ConstantinosDemOx** [Yelab2020/Cottrazm#19]
Hi,

Thank you for this amazing package. I have ran the script using extdata file and it works fine with no errors. But when I try to run the STModiCluster with my file I get this error: 

```

Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  KeyError: 'library_ids'
Run `reticulate::py_last_error()` for `details.


── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/rlibs/Cottrazm/python/Rusedtile.py", line 21, in ME_normalize
    data=st.Read10X(path = inDir)
  File "/TumorBoundary/lib/python3.8/site-packages/stlearn/wrapper/read.py", line 96, in Read10X
    library_id = str(attrs.pop("library_ids")[0], "utf-8")
KeyError: 'library_ids'

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─Cottrazm::STModiCluster(...)
 2.   └─reticulate (local) ME_normalize(inDir = InDir, outDir = OutDir, sample = Sample)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
See `reticulate::py_last_error()$r_trace$full_call` for more details.

Session info: Matrix products: default
BLAS/LAPACK: FlexiBLAS OPENBLAS;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/London
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] BiocManager_1.30.24    SeuratObject_5.0.2     Seurat_4.4.0          
 [4] Cottrazm_0.1.1         clusterProfiler_4.12.6 tibble_3.2.1          
 [7] ggrepel_0.9.6          data.table_1.16.2      quadprog_1.5-8        
[10] cowplot_1.1.3          scatterpie_0.2.3       openxlsx_4.2.7.1      
[13] reticulate_1.39.0      assertthat_0.2.1       dendextend_1.18.1     
[16] phylogram_2.1.0        infercnv_1.20.0        rtracklayer_1.64.0    
[19] GenomicRanges_1.56.1   GenomeInfoDb_1.40.1    IRanges_2.38.1        
[22] S4Vectors_0.42.1       readr_2.1.5            BiocGenerics_0.50.0   
[25] ggtree_3.12.0          patchwork_1.3.0        RColorBrewer_1.1-3    
[28] stringr_1.5.1          ggplot2_3.5.1          Matrix_1.7-0          
[31] dplyr_1.1.4            magrittr_2.0.3      
```

I would greatly appreciate your help with this!

**Comment by ConstantinosDemOx** [comment]
Hi, I have fixed the issue. In the Rusedtile.py, I added library_id = "sample" to the st.Read10X() function as this was giving me the error.
